/**
 * For this project, your job is to implement five methods as defined below.
 */
public class Example {
    public boolean not(boolean sayYes){
        return !sayYes;
    }
    /**
     * Create a method as described here:
     * - named "not"
     * - accepts a single boolean argument
     * - returns a boolean value
     *
     * This method returns the opposite of the value of the argument. EG: if the
     * method receives true for its argument, it will return false.
     */
    // todo: write not() method
        int x=5;
    public int doublePlusOne(int x){
        return x*2+1;
    }
    /**
     * Create a method as described:
     * - named "doublePlusOne"
     * - accepts one integer argument
     * - returns an integer value
     *
     * This method should double the provided argument and add one to it. The
     * resulting value is returned. EG: if the argument is 5, this method
     * returns 11.
     */
    // todo: write doublePlusOne() method
    double X=8.1;
    double Y=9.9;
        public double averageTwoNumbers(double x, double y){
            return (x+y)/2;
        }

    /**
     * Create a method as described:
     * - named "averageTwoNumbers"
     * - accepts two double arguments
     * - returns a double value
     *
     * This method returns the average of the two arguments. EG: 8.1 and 9.9 are
     * averaged to 9.
     */
    // todo: write averageTwoNumbers() method


    /**
     * Create a method as described:
     * - named "getGreeting"
     * - accepts a single String argument
     * - returns a String value
     *
     * This method should return a string that reads "Hello, {argument value}!",
     * where {argument value} is a placeholder for the String argument provided.
     * For example if the String argument is "Tracy", this method should return
     * "Hello, Tracy!".
     */
    // todo: write getGreeting() method
    public String getGreeting(String getGreeting){
        return "Hello, " + getGreeting + "!";
    }

    /**
     * Create a method as described:
     * - named "sayHello"
     * - accepts a single String argument
     * - returns nothing
     *
     * This method should print out the greeting generated by the getGreeting()
     * method. To be clear, this method must invoke the getGreeting() method and
     * print the resulting string to the console. EG: If the String argument is
     * "Tracy", this method should print out "Hello, Tracy!".
     */
    public void sayHello(String getGreeting){

        System.out.println( "Hello, " + getGreeting + "!");
    }
    // todo: write sayHello() method
}
